### ISSUE TITLE
gnulib dependency

### ISSUE THREAD

**Issue by efosler** [OSU-slatelab/ASR-CRaFT#8]
Add gnulib dependency to README.

**Comment by aestiff** [comment]
From the "For Developers" section:

> The configure script depends on gnulib for a couple of m4 macros to facilitate finding library
> dependencies and setting appropriate rpath variables for the compiled executables. Thus, for
> development you will have to install gnulib-tool and invoke it as described in ${topsrcdir}/m4/gnulib
> cache.m4. [Note that the gnulib source code contained in this package is distributed under the GPL in
> accordance with the Autoconf exception.

**Comment by efosler** [comment]
I think I missed this because I thought all dependencies were mentioned in the first paragraph.  Perhaps first itemize the list (union of the two) and then leave the paragraphs for exposition?

**Comment by aestiff** [comment]
Donezo.
